name: prosopagnosia
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: ^4.6.1
  hive: ^2.0.5
  image: ^3.1.3
  multiavatar: ^0.1.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/wood.png
